site_name: Portafolio de Mecatrónica
site_description: Documentación de prácticas y proyectos
site_author: Emmanuel Justo Flores

theme:
  name: material
  language: es
  
  # Paleta de colores y alternador de modo oscuro / claro
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  # Funcionalidades estéticas y de navegación
  features:
    - navigation.tabs          # Pestañas principales en el menú superior
    - navigation.sections      # Organización por secciones en la barra lateral
    - navigation.top           # Botón flotante para regresar arriba
    - navigation.path          # Muestra la ruta de navegación actual (breadcrumbs)
    - search.suggest           # Sugerencias automáticas en la barra de búsqueda
    - search.highlight         # Resalta palabras encontradas en la búsqueda
    - content.code.copy        # Agrega botón para copiar los bloques de código

# Extensiones para mejorar el formato de los documentos Markdown
markdown_extensions:
  - admonition                 # Bloques visuales de notas, avisos y alertas
  - pymdownx.details           # Cajas desplegables u ocultables
  - pymdownx.superfences       # Formato mejorado para bloques de código
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:           # Pestañas de contenido o código interactivo
      alternate_style: true
  - tables                     # Tablas formateadas
  - attr_list

plugins:
  - search
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Inicio: index.md
  - "Sobre Mí": SobreMi.md
  - "Prácticas":
      - "Practica 1": Practicas/Practica1.md
  - "Proyectos":
      - "Proyecto 1": Proyectos/Proyecto1.md
  - "Reflexiones":
      - "Vision Mecatronica": Reflexiones/VisionMecatronica.md
